import type { SiteImage } from "./types";

export const images: SiteImage[] = [
  {
    id: "hero-commercial-floors",
    src: "/images/stock/hero-commercial-floors.jpg",
    width: 1800,
    height: 1202,
    alt: "Polished commercial corridor and lounge with glass-walled offices",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://unsplash.com/photos/architectural-photography-of-black-and-brown-hallway-ZtC4_rPCRXA",
    photographer: "Nastuh Abootalebi",
    platform: "Unsplash",
    intendedSection: "Homepage hero",
  },
  {
    id: "polished-conference-floor",
    src: "/images/stock/polished-conference-floor.jpg",
    width: 1800,
    height: 1202,
    alt: "Sunlit conference room with a large polished commercial floor",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/QckxruozjRg",
    photographer: "Nastuh Abootalebi",
    platform: "Unsplash",
    intendedSection: "Floor care and results gallery",
  },
  {
    id: "commercial-office",
    src: "/images/stock/commercial-office.jpg",
    width: 1600,
    height: 1065,
    alt: "Open commercial office with polished floors and workstations",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/people-sitting-on-chair-in-front-of-computer-1170412/",
    photographer: "Startup Stock Photos",
    platform: "Pexels",
    intendedSection: "Commercial cleaning and offices",
  },
  {
    id: "facility-window-cleaning",
    src: "/images/stock/facility-window-cleaning.jpg",
    width: 1600,
    height: 2400,
    alt: "Professional cleaner washing large facility windows in a modern interior",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/man-in-red-overall-cleaning-the-window-6197122/",
    photographer: "Tima Miroshnichenko",
    platform: "Pexels",
    intendedSection: "Commercial cleaning service card and page",
  },
  {
    id: "commercial-carpet-cleaning",
    src: "/images/stock/commercial-carpet-cleaning.jpg",
    width: 1600,
    height: 2400,
    alt: "Worker cleaning carpet in a commercial entertainment space",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/man-wearing-uniform-cleaning-the-floor-8273515/",
    photographer: "cottonbro studio",
    platform: "Pexels",
    intendedSection: "Floor care carpet cleaning",
  },
  {
    id: "carpet-extraction",
    src: "/images/stock/carpet-extraction.jpg",
    width: 1600,
    height: 1200,
    alt: "Close-up of carpet cleaning equipment in use on a patterned carpet",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/black-vacuum-cleaner-4107284/",
    photographer: "cottonbro studio",
    platform: "Pexels",
    intendedSection: "Carpet cleaning and water extraction",
  },
  {
    id: "tile-grout-cleaning",
    src: "/images/stock/tile-grout-cleaning.jpg",
    width: 1600,
    height: 2134,
    alt: "Close-up of a brush scrubbing soapy tile and grout",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/cleaning-tiles-with-soap-and-scrub-brush-32908422/",
    photographer: "Alejandro Robles Duque",
    platform: "Pexels",
    intendedSection: "Tile and grout cleaning",
  },
  {
    id: "tile-surface-cleaning",
    src: "/images/stock/tile-surface-cleaning.jpg",
    width: 1600,
    height: 2400,
    alt: "Professional wiping a large dark tile surface",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/6195280/",
    photographer: "Tima Miroshnichenko",
    platform: "Pexels",
    intendedSection: "Floor and surface care",
  },
  {
    id: "interior-painting",
    src: "/images/stock/interior-painting.jpg",
    width: 1600,
    height: 1067,
    alt: "Painter rolling a wall with window protection and drop cloths in place",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/a-man-painting-the-wall-6474471/",
    photographer: "Thirdman",
    platform: "Pexels",
    intendedSection: "Painting and property turnovers",
  },
  {
    id: "paint-roller",
    src: "/images/stock/paint-roller.jpg",
    width: 1600,
    height: 1067,
    alt: "Close-up of a paint roller applying a coat to a wall",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/person-holding-paint-roller-1669754/",
    photographer: "Vecislavas Popa",
    platform: "Pexels",
    intendedSection: "Painting detail",
  },
  {
    id: "sheetrock-sanding",
    src: "/images/stock/sheetrock-sanding.jpg",
    width: 1600,
    height: 2397,
    alt: "Gloved hand sanding a prepared interior wall",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/5691606/",
    photographer: "Kateryna Babaieva",
    platform: "Pexels",
    intendedSection: "Sheetrock work",
  },
  {
    id: "sheetrock-trowel",
    src: "/images/stock/sheetrock-trowel.jpg",
    width: 1600,
    height: 2397,
    alt: "Close-up of a trowel finishing an interior wall corner",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/5691622/",
    photographer: "Kateryna Babaieva",
    platform: "Pexels",
    intendedSection: "Sheetrock and light repairs",
  },
  {
    id: "handyman-repair",
    src: "/images/stock/handyman-repair.jpg",
    width: 1600,
    height: 2396,
    alt: "Worker making interior repairs at a window during a property refresh",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/man-with-screwdriver-preparing-for-renovation-in-apartment-5768187/",
    photographer: "Ksenia Chernaya",
    platform: "Pexels",
    intendedSection: "Handyman and home repairs",
  },
  {
    id: "apartment-interior",
    src: "/images/stock/apartment-interior.jpg",
    width: 1800,
    height: 1200,
    alt: "Bright apartment living area prepared for occupancy",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/MP0bgaS_d1c",
    photographer: "Naomi Hebert",
    platform: "Unsplash",
    intendedSection: "Apartment turnovers",
  },
  {
    id: "apartment-living",
    src: "/images/stock/apartment-living.jpg",
    width: 1600,
    height: 1068,
    alt: "Furnished apartment living room with clean floors and carpet",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/1571468/",
    photographer: "Max Vakhtbovych",
    platform: "Pexels",
    intendedSection: "Move-in preparation",
  },
  {
    id: "apartment-community",
    src: "/images/stock/apartment-community.jpg",
    width: 1600,
    height: 1200,
    alt: "Multi-story apartment community exterior",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/439391/",
    photographer: "Pixabay",
    platform: "Pexels",
    intendedSection: "Apartment communities property type",
  },
  {
    id: "apartment-building",
    src: "/images/stock/apartment-building.jpg",
    width: 1800,
    height: 2400,
    alt: "Modern apartment building facade",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/cc1a3fa10c00",
    photographer: "Ján Jakub Naništa",
    platform: "Unsplash",
    intendedSection: "Apartment communities",
  },
  {
    id: "restaurant-interior",
    src: "/images/stock/restaurant-interior.jpg",
    width: 1800,
    height: 1200,
    alt: "Dining room in a restaurant and entertainment space",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/4c7edcad34c4",
    photographer: "Nick Karvounis",
    platform: "Unsplash",
    intendedSection: "Restaurants and entertainment spaces",
  },
  {
    id: "office-building",
    src: "/images/stock/office-building.jpg",
    width: 1600,
    height: 1066,
    alt: "Commercial office building exterior",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/white-and-blue-concrete-building-269077/",
    photographer: "Pixabay",
    platform: "Pexels",
    intendedSection: "Offices property type",
  },
  {
    id: "office-lounge",
    src: "/images/stock/office-lounge.jpg",
    width: 1800,
    height: 1200,
    alt: "Commercial common-area lounge with seating and large windows",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/TV2gg2kZD1o",
    photographer: "Inside Weather",
    platform: "Unsplash",
    intendedSection: "Commercial common areas",
  },
  {
    id: "office-bright",
    src: "/images/stock/office-bright.jpg",
    width: 1800,
    height: 1200,
    alt: "Bright office interior with large windows and a work ledge",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/856f4ea42174",
    photographer: "Aleksandar Jason",
    platform: "Unsplash",
    intendedSection: "Office cleaning",
  },
  {
    id: "residential-interior",
    src: "/images/stock/residential-interior.jpg",
    width: 1800,
    height: 1224,
    alt: "Residential living space with clean floors and open kitchen",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/ce8a6c25118c",
    photographer: "R ARCHITECTURE",
    platform: "Unsplash",
    intendedSection: "Residential services",
  },
  {
    id: "residential-kitchen",
    src: "/images/stock/residential-kitchen.jpg",
    width: 1600,
    height: 1068,
    alt: "Residential kitchen with finished wood floors",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/534151/",
    photographer: "Pixabay",
    platform: "Pexels",
    intendedSection: "Residential properties",
  },
  {
    id: "restroom-cleaning",
    src: "/images/stock/restroom-cleaning.jpg",
    width: 1600,
    height: 1067,
    alt: "Gloved hands cleaning a restroom sink and surrounding surfaces",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/4239113/",
    photographer: "Anete Lusina",
    platform: "Pexels",
    intendedSection: "Restrooms and shared spaces",
  },
  {
    id: "window-cleaning-detail",
    src: "/images/stock/window-cleaning-detail.jpg",
    width: 1600,
    height: 1067,
    alt: "Close-up of professional window cleaning with protective gloves",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/4239146/",
    photographer: "Anete Lusina",
    platform: "Pexels",
    intendedSection: "Commercial facility cleaning details",
  },
  {
    id: "finished-wood-floors",
    src: "/images/stock/finished-wood-floors.jpg",
    width: 1800,
    height: 2700,
    alt: "Clean finished wood flooring in a prepared interior",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/75bc0f6a952d",
    photographer: "Daniel McCullough",
    platform: "Unsplash",
    intendedSection: "Floor restoration presentation",
  },
  {
    id: "bathroom-tile",
    src: "/images/stock/bathroom-tile.jpg",
    width: 1800,
    height: 2699,
    alt: "Bathroom with a clean tile floor",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://unsplash.com/photos/5fefe8c9ef14",
    photographer: "Sidekix Media",
    platform: "Unsplash",
    intendedSection: "Tile cleaning and residential restrooms",
  },
  {
    id: "retail-interior",
    src: "/images/stock/retail-interior.jpg",
    width: 1600,
    height: 1067,
    alt: "Retail merchandising shelves in a store interior",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl:
      "https://www.pexels.com/photo/grayscale-photography-of-folded-clothes-1884581/",
    photographer: "Tembela Bohle",
    platform: "Pexels",
    intendedSection: "Retail properties",
  },
  {
    id: "home-ready",
    src: "/images/stock/home-ready.jpg",
    width: 1600,
    height: 1029,
    alt: "Open residential living and dining space ready for occupancy",
    sourceType: "stock",
    ownershipVerified: false,
    publicationApproved: false,
    sourceUrl: "https://www.pexels.com/photo/1571460/",
    photographer: "Max Vakhtbovych",
    platform: "Pexels",
    intendedSection: "Residential and turnover presentation",
  },
  {
    id: "patrick-moncur",
    src: "/images/company/patrick-moncur.jpg",
    width: 1431,
    height: 1600,
    alt: "Patrick Moncur, President of Power In Service Inc.",
    sourceType: "company",
    ownershipVerified: true,
    publicationApproved: true,
    sourceUrl: "",
    photographer: "Power In Service Inc.",
    platform: "Company",
    intendedSection: "About page owner portrait",
  },
];

export const imageById = Object.fromEntries(
  images.map((image) => [image.id, image]),
) as Record<string, SiteImage>;

export function getImage(id: string): SiteImage {
  const image = imageById[id];
  if (!image) {
    throw new Error(`Missing image: ${id}`);
  }
  return image;
}

export function publishedCompanyImages(): SiteImage[] {
  return images.filter(
    (image) =>
      image.sourceType === "company" &&
      image.ownershipVerified &&
      image.publicationApproved,
  );
}

export const representativeGalleryIds = [
  "hero-commercial-floors",
  "facility-window-cleaning",
  "polished-conference-floor",
  "carpet-extraction",
  "tile-grout-cleaning",
  "interior-painting",
] as const;
